### ISSUE TITLE
Spaces in UNC

### ISSUE THREAD

**Issue by Nibb31** [OpenMediaVault-Plugin-Developers/openmediavault-remoteshare#10]
My (ISP-provided) router allows SMB sharing of USB devices. Unfortunately, the name of the USB is hard coded as `Disque 1` with a space and cannot be changed on the router.

When I enter Disque 1 in the remoteshare UI, the UNC path is converted in /etc/fstab to `//<IP>/Disque\\0401` which fails to mount. If I manually edit /etc/fstab to `//<IP>/Disque\0401` then the remote share mounts properly.

So it seems that spaces should be converted to `\040` instead of `\\040`

**Comment by ryecoaaron** [comment]
It used to work and there should only be one backslash.  In the code - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-remoteshare/blob/master/usr/share/openmediavault/engined/rpc/remoteshare.inc#L695 - you will see four backslashes.  That is really two delimited backslashes for storage in config.xml.  Then when omv-mkconf remoteshare is executed, it sees one delimited backslash for writing to fstab.  I added this to the code almost three years ago.  I guess I will have to create an OMV 2.x vm to test this but I really didn't want to maintain any OMV 2.x plugins let alone this one.

**Comment by Nibb31** [comment]
Ouch! I just noticed that I filed this issue in the OMV 2 github. I'm having the issue in the OMV 3 remotemount plugin.
My apologies ! I'm closing this one and opening the issue in the proper plugin.

**Comment by ryecoaaron** [comment]
Oh.  I just spun up a VM and tested it :(
