### ISSUE TITLE
ftpfs module allow_other option

### ISSUE THREAD

**Issue by redvoodoochild** [OpenMediaVault-Plugin-Developers/openmediavault-remoteshare#9]
Hi excuse my poor english
ftpfs module does not mount with allow_other.. so we can't browse it with the other plugin (samba, owncloud..)

Thanks

**Comment by ryecoaaron** [comment]
Can you post your fstab line for the ftpfs share?  It definitely should have allow_other in it by default. Look at line 1883 here:  https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-remoteshare/blob/master/usr/share/openmediavault/engined/rpc/remoteshare.inc#L1883

**Comment by redvoodoochild** [comment]
Hi. This is my /etc/fstab :

curlftpfs#ftp://xxxxx:xxxx@srv.xxxxxxx.org//home /media/fb7a4552-b615-4f91-ad10-ad0cd6d777e6/srv.beurdin.org/ fuse rw,_netdev 0 0


I must add the "allow_other" option manually.

**Comment by ryecoaaron** [comment]
It was a typo when not using a file to store credentials.  I am fixing this now.  I recommend using a file to store the credential instead of storing them in fstab.

**Comment by redvoodoochild** [comment]
ok thanks a lot. Did you planned to add Sftp / sshfs mounting ?

**Comment by ryecoaaron** [comment]
It is written but doesn't work right with a password.  So, I didn't add it.  I haven't work on it in a while either.  Maybe in the coming weeks...

**Comment by redvoodoochild** [comment]
No problem.

thanks a lot for you work.
